<?php $formKey = $this->getBlockHtml('formkey'); ?>

<?php echo $this->getMessagesBlock()->toHtml() ?>
<ol class="opc">
	<li class="section allow active" id="opc-login">
		<div class="step-title">
            <h2><?php echo $this->__('Customer Account') ?></h2>
		</div>
		<div class="step">
			<ul class="messages">
				<li class="notice-msg">
					<ul>
						<li><?php echo $this->__('Dear customer we have received your billing and shipping information. In order to finish your order please create an account below or checkout as guest. ') ?></li>
					</ul>
				</li>
			</ul>
			<div class="col2-set">
			    <div class="col-1">
			        <h3><?php if( $this->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
			        <form id="register-form" action="<?php echo $this->escapeHtml($this->getRegisterPostAction()) ?>" method="post">
			        <fieldset>
			        	<?php echo $formKey; ?>
			        	<p><?php echo $this->__('Register with us for future convenience:') ?></p>
				        <?php if( $this->isAllowedGuestCheckout() ): ?>
				            <ul class="form-list">
				                <li class="control">
				                    <input type="radio" name="register_method" id="login:guest" value="guest" class="radio" checked="checked" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
				                </li>
				           	</ul>

				           	<ul id="guest-form-extra" class="form-list">
					        	<?php if (!$this->getUsername()) : ?>
						        	<li>
										<label for="guest-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
										<div class="input-box">
											<input type="text" class="input-text required-entry validate-email" id="guest-email" name="guest[email]" />
										</div>
									</li>
								<?php endif; ?>
					        </ul>

				           	<ul class="form-list">
				                <li class="control">
				                    <input type="radio" name="register_method" id="login:register" value="register" class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
				                </li>
				            </ul>
				        <?php else: ?>
				            <input type="hidden" name="register_method" id="login:register" value="register" checked="checked" />
				        <?php endif; ?>

						<ul id="register-form-extra" class="form-list">
							<li>
								<label for="register-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
								<div class="input-box">
									<input type="text" class="input-text required-entry validate-email" id="register-email" name="register[email]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
								</div>
							</li>
							<li>
								<label for="register-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
								<div class="input-box">
									<input type="password" class="input-text required-entry validate-password" id="register-password" name="register[customer_password]" />
								</div>
							</li>
							<li>
								<label for="register-confirm-password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
								<div class="input-box">
									<input type="password" class="input-text required-entry validate-cpassword" id="register-confirm-password" name="register[confirm_password]" />
								</div>
							</li>
						</ul>
					</fieldset>
					</form>
			    </div>
			    <div class="col-2">
			        <h3><?php echo $this->__('Login') ?></h3>
			        <form id="login-form" action="<?php echo $this->escapeHtml($this->getLoginPostAction()) ?>" method="post">
			        <fieldset>
			            <?php echo $formKey; ?>
			            <h4><?php echo $this->__('Already registered?') ?></h4>
			            <p><?php echo $this->__('Please log in below:') ?></p>
			            <ul class="form-list">
			                <li>
			                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
			                    <div class="input-box">
			                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
			                    </div>
			                </li>
			                <li>
			                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
			                    <div class="input-box">
			                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
			                    </div>
			                </li>
			            </ul>
			        </fieldset>
			        </form>
			    </div>
			</div>
			<div class="col2-set">
			    <div class="col-1">
			        <div class="buttons-set">
			            <p class="required">&nbsp;</p>
			            <button type="button" class="button" onclick="submitRegister(this)"><span><span><?php echo ($this->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?></span></span></button>
			        </div>
			    </div>
			    <div class="col-2">
			        <div class="buttons-set">
			            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
			            <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
			            <button type="button" class="button" onclick="submitLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
			        </div>
			    </div>
			</div>
			<script type="text/javascript">
			//<![CDATA[
			   	<?php if( $this->isAllowedGuestCheckout() ): ?>
				$('register-form-extra').hide();
				$('login:guest').observe('change', function(){
					$('guest-form-extra').show();
					$('register-form-extra').hide();
				});
				$('login:register').observe('change', function(){
					$('guest-form-extra').hide();
					$('register-form-extra').show();
				});
				<?php endif; ?>

			    var registerForm = new VarienForm('register-form', true);
			    $('register-email').observe('keypress', bindRegisterPost);
			    $('register-password').observe('keypress', bindRegisterPost);
			    $('register-confirm-password').observe('keypress', bindRegisterPost);
			    function bindRegisterPost(evt){
			        if (evt.keyCode == Event.KEY_RETURN) {
			        	registerForm.submit();
			        }
			    }
			    function submitRegister(button)
			    {
			        if(registerForm.validator && registerForm.validator.validate()){
			            button.disabled = true;
			            registerForm.submit();
			        }
			    }

			    var loginForm = new VarienForm('login-form', true);
			    $('login-email').observe('keypress', bindLoginPost);
			    $('login-password').observe('keypress', bindLoginPost);
			    function bindLoginPost(evt){
			        if (evt.keyCode == Event.KEY_RETURN) {
			            loginForm.submit();
			        }
			    }
			    function submitLogin(button)
			    {
			        if(loginForm.validator && loginForm.validator.validate()){
			            button.disabled = true;
			            loginForm.submit();
			        }
			    }
			//]]>
			</script>
		</div>
	</li>
</ol>