<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>

<?php if (!$this->getQuote()->isVirtual()) : ?>
	<ol class="opc">
		<li class="section allow active">
			<div class="step-title">
	            <span class="number">1</span>
	            <h2><?php echo $this->__('Shipping Method') ?></h2>
	        </div>
			<div class="step">

				<?php $_shippingRateGroups = $this->getShippingRates(); ?>
				<dl class="sp-methods">
					<?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
						<dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
						<dd>
							<ul>
								<?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
									<li>
									   <?php if ($_rate->getErrorMessage()): ?>
											<ul class="messages"><li class="error-msg"><ul><li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li></ul></li></ul>
									   <?php else: ?>
											<?php if ($_sole) : ?>
												<span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $this->escapeHtml($_rate->getCode()) ?>" id="s_method_<?php echo $this->escapeHtml($_rate->getCode()) ?>" checked="checked" /></span>
											<?php else: ?>
												<input onchange="$('external-checkout-save-shipping-method-button').click();" name="shipping_method" type="radio" value="<?php echo $this->escapeHtml($_rate->getCode()) ?>" id="s_method_<?php echo $this->escapeHtml($_rate->getCode()) ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>
											<?php endif; ?>

											<label for="s_method_<?php echo $this->escapeHtml($_rate->getCode()) ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
												<?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
												<?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
												<?php echo $_excl; ?>
												<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
													(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
												<?php endif; ?>
											</label>
									   <?php endif ?>
									</li>
								<?php endforeach; ?>
							</ul>
						</dd>
					<?php endforeach; ?>
				</dl>

				<button id="external-checkout-save-shipping-method-button" type="submit" class="no-display"></button>
			</div>
		</li>
	</ol>
<?php endif; ?>