<?php if ($this->canCaptureNoClose()) : ?>
<script type="text/javascript">
document.observe('dom:loaded', function(){
	function insertCaptureClose() {
		var html = '<p>';
		html += '<label class="normal" for="capture_no_close"><?php echo str_replace("'", "\'", $this->__("Capture: Don't Close")) ?></label> ';
		html += '<input id="capture_no_close" name="invoice[capture_no_close]" value="1" type="checkbox" />';
		html += '</p>';
		$$('.order-totals-bottom p:first')[0].insert({after: html});
		$$('select[name="invoice[capture_case]"]')[0].on('change', function(){
			$('capture_no_close').disabled = ($F($('edit_form')['invoice[capture_case]']) != 'online');
		});
		$('capture_no_close').disabled = ($F($('edit_form')['invoice[capture_case]']) != 'online');
	}
	insertCaptureClose();

	var isInSubmitAndReloadArea = false;
	window.submitAndReloadArea = window.submitAndReloadArea.wrap(function(callOriginal, a, b){
		isInSubmitAndReloadArea = true;
		return callOriginal(a, b);
	});

	Element.update = Element.update.wrap(function(callOriginal, element, newContent){
		var result = callOriginal(element, newContent);
		if (isInSubmitAndReloadArea) {
			insertCaptureClose();
		}
		return result;
	});

	Element.addMethods({
		update: Element.update
	});
});
</script>
<?php endif; ?>